.PHONY: docker-compose/build docker-compose/down docker-compose/logs docker-compose/up

docker-compose/build:
	docker-compose build

docker-compose/up:
	docker-compose up -d

docker-compose/down:
	docker-compose down

docker-compose/logs:
	docker-compose logs -f
