version: '3'

services:
  terraform:
    image: hashicorp/terraform:0.14.9
    volumes:
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
      - ./:/app/
    working_dir: /app/
#    environment:
#      - AWS_PROFILE=${AWS_PROFILE:-zucks-zgok}
#      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-northeast-1}
